### PR TITLE
#33 updated Deploy.patch to prevent unintended restarts

### PR DESCRIPTION
**Pull request by MaxTrautwein**
Noticed the production environment going down, 
added `restart: unless-stopped` to prevent that

### CODE REVIEW

**Comment by Ebenezer2077** [comment]
hast dus schon getestet?

**Comment by MaxTrautwein** [comment]
klar

**Review by Ebenezer2077 — APPROVED** [review]
looks good to me

**Comment by MaxTrautwein** [comment]
hmm i thought that was fixed, but it seems like it still happens
more testing needed

**Comment by MaxTrautwein** [comment]
`sudo loginctl enable-linger $(whoami)` seems to fix it

**Pull request merged**
